// Código Java que se incluirá en el parser
package Bizlang;
import java_cup.runtime.*;
import bizlang.Inventario;
import java_cup.runtime.Symbol;

// Definir tokens provenientes del analizador léxico (JFlex)
terminal String TEXTO;
terminal String COMANDO;
terminal Integer NUMERO;

// Definir no terminales
nonterminal programa, comando;

// Definir el inicio del análisis sintáctico
start with programa;

// Reglas de producción del lenguaje
programa ::= comando;

comando ::=
    COMANDO TEXTO NUMERO
    {:
    if ($1.equals("agregar")){
        System.out.println("🛒 Agregando " + $2 + " con cantidad " + $3);
        }
    :}

    {:
    if ($1.equals("vender")){
        System.out.println("Se vende " + $2 + "con el precio " + $3);
        Inventario.registrarVenta($2, $3.intValue());
        }
    :}

    {:
    if ($1.equals("mostrar_inventario")){
        System.out.println("Mostrando inventario...");
        }
    :}

    {:
    if ($1.equals("generar_reporte")){
        System.out.println("Generando reporte de ventas...");
        Inventario.generReportePDF();
        }
    :}
;
